"""add_serial_number_to_purchase_items

Revision ID: 782f9987ccc4
Revises: 1ff27cf3578c
Create Date: 2026-05-12 23:25:02.579785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782f9987ccc4'
down_revision: Union[str, None] = '1ff27cf3578c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificamos si la columna ya existe antes de intentar crearla (para evitar errores en producción)
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='purchase_items' AND column_name='serial_number'"))
    if not res.first():
        op.add_column('purchase_items', sa.Column('serial_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'serial_number')
    # ### end Alembic commands ###
